language: python
python:
  - '3.6'
install:
  - 'pip install -r requirements-dev.txt'
script: 'python -m pytest --cov=test --cov-report=xml'
after_success:
  - 'python-codacy-coverage -r coverage.xml'
